- name: Wait until Solr status is 200
  uri:
    url: 'http://localhost:8080/api/admin/index'
    return_content: yes
    validate_certs: no
    status_code:
      - 200
  until: uri_output.status == 200
  retries: 50 # 60 retries * 5 seconds == 5 minutes
  delay: 5
  register: uri_output
