---

# dataverse/tasks/dataverse-metadata.yml

- name: flushing handlers to start glassfish if needed
  meta: flush_handlers

- name: Updating metadata
  debug:
    msg: '##### UPDATING METADATA #####'

- name: Copy citation.tsv
  copy:
    src: citation.tsv
    dest: /tmp/citation.tsv
    mode: '0600'

- name: Add citation.tsv to dataverse
  shell: 'curl http://localhost:8080/api/admin/datasetfield/load -H "Content-type: text/tab-separated-values" -X POST --upload-file /tmp/citation.tsv'
  notify: enable and restart glassfish

- name: update Solr schema
  script: 'updateSchemaMDB.sh -t {{ dataverse.solr.root }}/server/solr/collection1/conf'