---

- ansible.builtin.import_tasks: dataverse-get-apitoken.yml

- name: call apitoken generator if no apitoken in DB
  ansible.builtin.import_tasks: dataverse-generate-apitoken.yml
  when: api_token is not defined or api_token == ''
