---
# dataverse/tasks/dataverse-apache.yml

- name: begin apache task
  debug:
    msg: '##### APACHE/HTTPD #####'

- name: httpd variables
  set_fact:
    apache_config_base_dir: "{{ (ansible_os_family == 'RedHat') | ternary ('/etc/httpd', '/etc/apache2') }}"

- name: httpd variables for RedHat/CentOS
  set_fact:
    apache_virtualhost_dir: "{{ apache_config_base_dir }}/conf.d"
    apache_config_dir: "{{ apache_config_base_dir }}/conf.d"
  when: ansible_os_family == "RedHat"

- name: httpd variables for Debian/Ubuntu
  set_fact:
    apache_virtualhost_dir: "{{ apache_config_base_dir }}/sites-enabled"
    apache_config_dir: "{{ apache_config_base_dir }}/conf-enabled"
  when: ansible_os_family == "Debian"

- name: install Apache for RedHat/CentOS
  yum: 
    name: ['httpd', 'mod_ssl']
    state: latest
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: install Apache for Debian/Ubuntu
  package:
    name: apache2
    state: latest
  when: ansible_os_family == "Debian"
  notify: enable and restart apache

- name: enable apache mods on Debian
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - proxy
    - proxy_http
  when: ansible_os_family == "Debian"    ## CHECKME -- does this need to be Debian-specific?
  notify: enable and restart apache

- name: disable default Debian site
  file:
    path: "{{ apache_virtualhost_dir }}/000-default.conf"
    state: absent
  when: ansible_os_family == "Debian"
  notify: enable and restart apache

- name: install http proxy when SSL disabled
  template:
    src: http.proxy.conf.j2
    dest: "{{ apache_virtualhost_dir }}/http.proxy.conf"
    owner: root
    group: root
    mode: '0644'
  when: apache.ssl.enabled == false
  notify: enable and restart apache

- include: dataverse-apache-ssl.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"
    - apache.ssl.enabled == true
    - letsencrypt.enabled == false

- include: certbot.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"
    - apache.ssl.enabled == true
    - letsencrypt.enabled == true

- name: install proxy error boilerplate
  copy: src=503.html dest="{{ apache_config_dir }}" owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  notify: enable and restart apache

- name: run handlers -- this runs the apache restart scripts
  meta: flush_handlers
