
- name: define describo-related settings
  set_fact:
    arp_settings:
     - name: arp.script.path
       value: /var/www/arp-kiserletek/cedarTemplateConverter/cedarTemplateConverter.py
     - name: arp.python.path
       value: /usr/bin/python3
     - name: dv.api.key
       value: "{{ api_token }}"
     - name: dv.host
       value: https://{{ site_fqdn }}
     - name: dv.updater.script.path
       value: "{{ dataverse.srcdir }}/conf/solr/8.11.1/update-fields.sh"
     - name: solr.host
       value: http://localhost:8983
     - name: solr.schema.path
       value: /usr/local/solr/server/solr/collection1/conf/schema.xml
     - name: describo.host
       value: "{{ describo.host }}"
     - name: solr.collection.name
       value: collection1
     - name: describo.secret
       value: "{{ describo.secret }}"

- set_fact:
    arp_settings: '{{ arp_settings | rekey_on_member("name") }}'

- name: set solr.schema.path group writable
  file:
    path: "{{ arp_settings['solr.schema.path'].value }}"
    mode: 0664
- name: add payara user to solr group to allow editing of solr.schema.path
  user:
    name: "{{ dataverse.payara.user }}"
    groups: "{{ dataverse.solr.group }}"
    append: true

#- debug:
#    var: arp_settings
#
#- debug:
#    var: arp_settings[item].value
##    var: "{{ arp_settings[item.item] }}"
#  with_items: "{{ arp_settings }}"


- name: get describo-related settings
  shell: "{{ payara_dir }}/bin/asadmin list-jvm-options | grep {{ item }}= | sed 's/.*=//'"
  register: current_arp_settings
  changed_when: false
  with_items: "{{ arp_settings }}"

#- debug:
#    var: item.stdout
#  with_items: "{{ current_arp_settings.results }}"

- name: calculate changed_arp_settings
  set_fact:
    changed_arp_settings: "{{ (arp_settings[item.item].value == item.stdout) |
                              ternary(changed_arp_settings,
                                      changed_arp_settings + [ {'name': item.item, 'value': item.stdout } ] )
                           }}"
  with_items: "{{ current_arp_settings.results }}"
  vars:
    changed_arp_settings: []

#- debug:
#    var: changed_arp_settings

- name: delete changed describo-related settings
  command: "{{ payara_dir }}/bin/asadmin delete-jvm-options \"-D{{ item.name }}={{ item.value | replace(':','\\:') }}\"" 
  with_items: "{{ changed_arp_settings }}"

#- debug:
#    var: changed_arp_settings

- name: configure describo-related settings
  command: "{{ payara_dir }}/bin/asadmin create-jvm-options \"-D{{ item.name }}={{ arp_settings[item.name].value | replace(':','\\:') }}\"" 
  with_items: "{{ changed_arp_settings }}"

- name: set cedar key
  uri:
    url: http://localhost:8080/api/admin/arp/setCedarKey
    method: POST
    body: '{"userIdentifier": "dataverseAdmin", "cedarKey": "{{ cedar.key }}"}'
    body_format: json
    status_code: 200

- name: set cedar services base domain
  uri:
    method: PUT
    url: http://localhost:8080/api/admin/settings/arp.cedar.domain
    body: "http://localhost:{{ cedar.domain }}"
    status_code: 200

- name: set aroma address
  uri:
    method: PUT
    url: http://localhost:8080/api/admin/settings/arp.aroma.address
    body: "https://{{ describo.host }}"
    status_code: 200

- name: set solr updater address
  uri:
    method: PUT
    url: http://localhost:8080/api/admin/settings/arp.solr.updater.address
    body: "http://localhost:{{ solr_updater.port }}"
    status_code: 200
