---

- name: instrument warfile
  debug:
    msg: '##### INSTRUMENT WARFILE #####'

- name: need a working directory
  file:
    path: '{{ dataverse.tmpdir }}/dvinstall/jacoco'
    owner: root
    group: root
    state: directory

- name: copy dataverse.war
  copy:
    src: '{{ dataverse.tmpdir }}/dvinstall/dataverse.war'
    dest: '{{ dataverse.tmpdir }}/dvinstall/jacoco/dataverse.war'
    remote_src: yes

- name: explode warfile
  shell: 'jar xf dataverse.war'
  args:
    chdir: '{{ dataverse.tmpdir }}/dvinstall/jacoco'

- name: rename classes directory
  command: mv {{ dataverse.tmpdir }}/dvinstall/jacoco/WEB-INF/classes {{ dataverse.tmpdir }}/dvinstall/jacoco/WEB-INF/classes-orig

- name: instrument classes
  shell: 'java -jar {{ dataverse.jacoco.home }}/lib/jacococli.jar instrument WEB-INF/classes-orig/ --dest WEB-INF/classes'
  args:
    chdir: '{{ dataverse.tmpdir }}/dvinstall/jacoco'

- name: create new warfile
  shell: 'jar cf {{ dataverse.tmpdir }}/dvinstall/dataverse.war *'
  args:
    chdir: '{{ dataverse.tmpdir }}/dvinstall/jacoco'
