---

- name: install rserve
  debug:
    msg: '##### BEGIN RSERVE INSTALLATION #####'

- name: ensure EPEL is installed
  yum:
    name: epel-release
    state: latest
  when: ansible_os_family == "RedHat"

- name: RHEL8 needs codeready-builder
  rhsm_repository:
    name: codeready-builder-for-rhel-8-x86_64-rpms
  when: ansible_distribution == "RedHat" and
        ansible_distribution_major_version == "8"

- name: CentOS8 needs PowerTools
  shell: "dnf config-manager --enable PowerTools"
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "8"

- name: install base packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - R-core
    - R-core-devel
  when: ansible_os_family == "RedHat"

- name: install base packages
  package:
    name: r-base-core, r-base-dev
  when: ansible_os_family == "Debian"

- name: detect number of system cores
  set_fact:
    num_cores: '{{ ansible_processor_vcpus }}'

- name: ensure .R exists
  file:
    path: '~/.R'
    state: directory

- name: set in .R/Makevars
  lineinfile:
    path: '~/.R/Makevars'
    line: 'MAKEFLAGS = -j{{ num_cores }}'
    state: present
    create: yes

- name: install R modules
  command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{item}}' %in% installed.packages()[,'Package'])) install.packages('{{item}}', repos=c('https://cloud.r-project.org/', Ncpus='{{ num_cores }}'))"
  with_items:
  - R2HTML
  - rjson
  - DescTools
  - Rserve
  - haven

- name: create R user and group
  user:
    name: '{{ rserve.user }}'

- name: install Rserv.conf
  template:
    src: Rserv.conf.j2
    dest: /etc/Rserv.conf
    owner: root
    group: root
    mode: '0644'

- name: install Rserv.pwd
  template:
    src: Rserv.pwd.j2
    dest: /etc/Rserv.pwd
    owner: '{{ rserve.user }}'
    group: '{{ rserve.group }}'
    mode: '0600'

- name: install rserve.service systemd unit file
  template:
    src: rserve.service.j2
    dest: /usr/lib/systemd/system/rserve.service
    owner: root
    group: root
    mode: '0644'

- name: reload systemd, enable rserve, start
  systemd:
    name: rserve
    enabled: yes
    daemon_reload: yes
    state: started
