---

- ansible.builtin.import_tasks: aws_cli.yml

- name: ensure dot dir exists
  file:
    path: '~{{ dataverse.payara.user }}/.aws'
    state: directory
    owner: '{{ dataverse.payara.user }}'
    group: '{{ dataverse.payara.group }}'
    mode: '0700'
    
- name: place aws credentials
  template:
    src: aws_credentials.j2
    dest: '~{{ dataverse.payara.user }}/.aws/credentials'
    owner: '{{ dataverse.payara.user }}'
    group: '{{ dataverse.payara.group }}'
    mode: '0600'

- name: place aws config
  template:
    src: aws_config.j2
    dest: '~{{ dataverse.payara.user }}/.aws/config'
    owner: '{{ dataverse.payara.user }}'
    group: '{{ dataverse.payara.group }}'
    mode: '0600'

- name: set storage-driver-id to {{ s3[0].storage_driver_id }}
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.storage-driver-id" "{{ s3[0].storage_driver_id }}"'

- name: set storage type to s3
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.{{ item.storage_driver_id }}.type" "{{ item.files_type }}"'
  with_items: '{{ s3 }}'

- name: set profile name
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.{{ item.storage_driver_id }}.profile" "{{ item.storage_driver_id }}"'
  with_items: '{{ s3 }}'

- name: set storage label
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.{{ item.storage_driver_id }}.label" "{{ item.label }}"'
  with_items: '{{ s3 }}'

- name: set s3 bucket name
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.{{ item.storage_driver_id }}.bucket-name" "{{ item.bucket_name }}"'
  with_items: '{{ s3 }}'

- name: set s3 url expiration minutes
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.{{ item.storage_driver_id }}.url-expiration-minutes" "{{ item.url_expiration_minutes }}"'
  with_items: '{{ s3 }}'

# optional s3 settings

- name: expose custom_endpoint_url as variable
  set_fact:
    custom_endpoint_urls: '{{ custom_endpoint_urls }} + [ {{ item.custom_endpoint_url }} ]'
  with_items: '{{ s3 }}'
  vars:
    custom_endpoint_urls: []

- name: create S3 bucket
  shell:
    'aws s3api create-bucket --bucket {{ item.bucket_name }}'
  args:
    executable: /bin/bash
  become_user: '{{ dataverse.payara.user }}'
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:/usr/local/bin"
  when: item.create_bucket == true
    and custom_endpoint_urls | length == 0
  with_items: '{{ s3 }}'

- name: "place s3_cors.json template"
  template:
    src: s3_cors.json.j2
    dest: '~{{ dataverse.payara.user }}/s3_cors.json'
    owner: '{{ dataverse.payara.user }}'
    group: '{{ dataverse.payara.group }}'
    mode: 0644
  when: (item.download_redirect == true or item.upload_redirect == true)
    and item.cors_already_set == false
  with_items: '{{ s3 }}'

- name: enable CORS on S3 bucket
  shell:
    'aws s3api put-bucket-cors --bucket {{ item.bucket_name }} --cors-configuration file://~{{ dataverse.payara.user }}/item_cors.json'
  args:
    executable: /bin/bash
  become: yes
  become_user: '{{ dataverse.payara.user }}'
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:/usr/local/bin"
  when: (item.download_redirect == true or item.upload_redirect == true)
    and custom_endpoint_url | length == 0
    and item.cors_already_set == false
  with_items: '{{ s3 }}'

- ansible.builtin.import_tasks: s3_custom_endpoint_url.yml
  when: custom_endpoint_urls | length > 0

- name: set s3 direct download
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.{{ item.storage_driver_id }}.download-redirect" "{{ item.download_redirect }}"'
  when: item.download_redirect == true
  with_items: '{{ s3 }}'

- name: set s3 direct upload
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.{{ item.storage_driver_id }}.upload-redirect" "{{ item.upload_redirect }}"'
  when: item.upload_redirect == true
  with_items: '{{ s3 }}'

- name: set s3 path style access
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.{{ item.storage_driver_id }}.path-style-access" "{{ item.path_style_access }}"'
  when: item.path_style_access == true
  with_items: '{{ s3 }}'

- name: set s3 payload signing
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.{{ item.storage_driver_id }}.payload-signing" "{{ item.payload_signing }}"'
  when: item.payload_signing == true
  with_items: '{{ s3 }}'

- name: turn chunked encoding off
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.{{ item.storage_driver_id }}.chunked-encoding" "{{ item.chunked_encoding }}"'
  when: item.chunked_encoding == false
  with_items: '{{ s3 }}'

- name: set custom endpoint region
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.{{ item.storage_driver_id }}.custom-endpoint-region" "{{ item.custom_endpoint_region }}"'
  when: item.custom_endpoint_region is defined and item.custom_endpoint_region != ''
  with_items: '{{ s3 }}'

- name: install s3fs
  package:
    name: s3fs
  when: s3[0].mapped_directory is defined and s3[0].mapped_directory != ''

#- name: create directory for mapping with fuse if configured
#  file:
#    path: "{{ item.mapped_directory }}"
#    state: directory
#    owner: '{{ dataverse.payara.user }}'
#    group: '{{ dataverse.payara.group }}'
#  when: item.mapped_directory is defined and item.mapped_directory != ''
#  with_items: '{{ s3 }}'

#- name: create s3fs credentials file
#  lineinfile:
#    path: /root/.passwd-s3fs
#    regex: '{{ item.access_key }}'
#    line: '{{ item.access_key }}:{{ item.secret_access_key }}'
#    create: true
#    mode: 0600
#  when: item.mapped_directory is defined and item.mapped_directory != ''
#  with_items: '{{ s3 }}'

#- name: mount mapped directory with fuse if configured
#  shell: 's3fs {{ item.bucket_name }} {{ item.mapped_directory }} -o url={{ item.custom_endpoint_url }} -o use_path_request_style,profile={{ item.storage_driver_id }}' #,uid=<usr>,gid=<grp>,allow_other
#  args:
#    executable: /bin/bash
#  become: yes
#  become_user: '{{ dataverse.payara.user }}'
#  when: item.mapped_directory is defined and item.mapped_directory != ''
#  with_items: '{{ s3 }}'

#- name: create fstab entries
#  lineinfile:
#    path: /etc/fstab
#    regex: '^s3fs.{{ item.bucket_name }}'
#    line: "s3fs#{{ item.bucket_name }} {{ item.mapped_directory }} fuse _netdev,allow_other,umask=227,uid=1002,gid=1002,use_path_request_style,profile={{ item.storage_driver_id }},url={{ item.custom_endpoint_url }}"
#  when: item.mapped_directory is defined and item.mapped_directory != ''
#  with_items: '{{ s3 }}'

- name: get dataverse user uid
  getent:
    database: passwd
    key: '{{ dataverse.payara.user }}'
- ansible.builtin.debug:
    var: ansible_facts.getent_passwd['dataverse']

- name: create fstab entries
  mount:
    src: "s3fs#{{ item.bucket_name }}"
    path: "{{ item.mapped_directory }}"
    fstype: fuse
    opts: "_netdev,allow_other,umask=227,uid={{ ansible_facts.getent_passwd['dataverse'][1] }},gid={{ ansible_facts.getent_passwd['dataverse'][2] }},use_path_request_style,profile={{ item.storage_driver_id }},url={{ item.custom_endpoint_url }}"
    state: mounted
  when: item.mapped_directory is defined and item.mapped_directory != ''
  with_items: '{{ s3 }}'

- name: set s3 storage mapping if configured
  shell: 'asadmin-create-or-replace-option.sh "dataverse.files.{{ item.storage_driver_id }}.directory" "{{ item.mapped_directory }}"'
  when: item.mapped_directory is defined and item.mapped_directory != ''
  with_items: '{{ s3 }}'
